### ISSUE TITLE
Could you please explain details of your fine-tune process？

### ISSUE THREAD

**Issue by drxmy** [tuner007/paraphrase#1]
I tried your model on the hugging face page. The results are great. But I want to do the task on Chinese. I have got the Chinese pretrained PEGASUS. I am not sure how to fine tune it in paraphrase sentences task.

**Comment by tuner007** [comment]
Hi @drxmy,

For finetunning you can check the official source https://github.com/google-research/pegasus
I have used the same script provided by them with minimal changes.

**Comment by drxmy** [comment]
> Hi @drxmy,
> 
> For finetunning you can check the official source https://github.com/google-research/pegasus
> I have used the same script provided by them with minimal changes.

Thank you! I will give it a try.
